version: 0.1

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install --global yarn
  pre_build:
    commands:
      - echo Installing source NPM dependencies... it wont install anything
      - yarn
  build:
    commands:
      - echo test started on `date`
      - echo running test
      - yarn run test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - HelloWorld.js